---
- hosts: all
  name: Create AWS Resources
  connection: local
  gather_facts: False
  tasks: 
   - name: Ping local machine 
     ping:
   
   - name: Create AWS EC2 Instances
     ec2:
      image: ami-0123b531fc646552f
      region: ap-south-1
      instance_type: t2.micro
      instance_tags:
        project: AnsibleScaling
      count_tag:
        project: AnsibleScaling
      # set exact_count to 0 to delete the instances
      exact_count: 2